# Generated by Django 2.1.3 on 2018-11-16 01:53

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('demonstration', 'User')
    Comment = apps.get_model('demonstration', 'Comment')
    BlogPost = apps.get_model('demonstration', 'BlogPost')
    Blog = apps.get_model('demonstration', 'Blog')

    blog_1 = Blog.objects.create(
        name='Stormlight Archives Blog',
    )
    user_1 = User.objects.create(
        username='user1',
        name='Dalinar',
    )
    user_2 = User.objects.create(
        username='user2',
        name='Kaladin',
    )
    user_3 = User.objects.create(
        username='user3',
        name='Shallan',
    )

    bp_1 = BlogPost.objects.create(
        title='Dalinar\'s Blog Post',
        body='.........',
        author=user_1,
        blog=blog_1,
    )
    bp_2 = BlogPost.objects.create(
        title='Shallan\'s Blog Post',
        body='.........',
        author=user_3,
        blog=blog_1,
    )

    Comment.objects.create(
        author=user_2,
        post=bp_1,
        comment='.........',
    )
    Comment.objects.create(
        author=user_3,
        post=bp_1,
        comment='.........',
    )
    Comment.objects.create(
        author=user_1,
        post=bp_1,
        comment='.........',
    )
    Comment.objects.create(
        author=user_2,
        post=bp_2,
        comment='.........',
    )
    Comment.objects.create(
        author=user_1,
        post=bp_2,
        comment='.........',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
